name: benchmark

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  DISTRIBUTION: 'temurin'
  GRADLE_COMMAND: './gradlew --no-daemon'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      benchmarks: ${{ steps.set-benchmarks.outputs.benchmarks }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: ${{ env.DISTRIBUTION }}
      - id: set-benchmarks
        run: echo "benchmarks=`./gradlew -q benchmarkJson`" >> $GITHUB_OUTPUT
  benchmark:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        jdk: [ 8, 11, 17, 21 ]
        microbenchmark: ${{fromJSON(needs.setup.outputs.benchmarks)}}
    name:  ${{ matrix.microbenchmark }} Java${{ matrix.jdk }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.jdk }}
          distribution: ${{ env.DISTRIBUTION }}
      - name: JMH
        run: ${{ env.GRADLE_COMMAND }} clean jmh -Dbenchmark=${{ matrix.microbenchmark }}
