name: benchmark

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  DISTRIBUTION: 'temurin'
  GRADLE_COMMAND: './gradlew --no-daemon'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: ${{ env.DISTRIBUTION }}
      - id: set-matrix
        run: echo "::set-output name=matrix::`./gradlew -q benchmarkJson`"
  benchmark:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        jdk: [ 8, 21 ]
        microbenchmark: ${{fromJSON(needs.setup.outputs.matrix)}}
    name:  ${{ matrix.microbenchmark }} ${{ matrix.jdk }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.jdk }}
          distribution: ${{ env.DISTRIBUTION }}
      - name: JMH
        run: ${{ env.GRADLE_COMMAND }} clean jmh -Dbenchmark=${{ matrix.microbenchmark }}
